plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.aronplayer'
version = '1.0.0'

android {
  namespace "expo.modules.aronplayer"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  def media3 = "1.9.0"
  implementation "androidx.media3:media3-common:${media3}"
  implementation "androidx.media3:media3-exoplayer:${media3}"
  implementation "androidx.media3:media3-exoplayer-dash:${media3}"
  implementation "androidx.media3:media3-exoplayer-hls:${media3}"
  implementation "androidx.media3:media3-exoplayer-smoothstreaming:${media3}"
  implementation "androidx.media3:media3-datasource:${media3}"
  implementation "androidx.media3:media3-ui:${media3}"
}
